# Generated by Django 2.0.6 on 2019-05-15 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=40, null=True)),
                ('author', models.CharField(max_length=80, null=True)),
                ('marketing_price', models.FloatField(null=True)),
                ('dangdang_price', models.FloatField(null=True)),
                ('sales_num', models.IntegerField(null=True)),
                ('stock', models.IntegerField(null=True)),
                ('press', models.CharField(max_length=60, null=True)),
                ('cover_pics', models.TextField(null=True)),
                ('words', models.IntegerField(null=True)),
                ('pages', models.SmallIntegerField(null=True)),
                ('book_size', models.SmallIntegerField(null=True)),
                ('paper_type', models.CharField(max_length=20, null=True)),
                ('packing_type', models.CharField(max_length=20, null=True)),
                ('version', models.SmallIntegerField(null=True)),
                ('printing_index', models.SmallIntegerField(null=True)),
                ('isbn', models.CharField(db_column='ISBN', max_length=50, null=True)),
                ('publish_time', models.DateField(null=True)),
                ('printint_time', models.DateField(null=True)),
                ('recommend', models.TextField(null=True)),
                ('content_intro', models.TextField(null=True)),
                ('author_intro', models.TextField(null=True)),
                ('catalog', models.TextField(null=True)),
                ('comments', models.TextField(null=True)),
                ('experpt_pics', models.TextField(null=True)),
                ('status', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'book_info',
            },
        ),
        migrations.CreateModel(
            name='GoodsList',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('book_num', models.IntegerField(null=True)),
                ('book_price', models.FloatField(null=True)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bookapp.BookInfo')),
            ],
            options={
                'db_table': 'goods_list',
            },
        ),
        migrations.CreateModel(
            name='TCatogray',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('catogry_name', models.CharField(max_length=40, null=True)),
                ('parent_id', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 't_catogray',
            },
        ),
        migrations.CreateModel(
            name='TDelivery',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('receiver_name', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('zipt_code', models.CharField(max_length=6, null=True)),
                ('telephone', models.CharField(max_length=12, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('status', models.CharField(max_length=40, null=True)),
            ],
            options={
                'db_table': 't_delivery',
            },
        ),
        migrations.CreateModel(
            name='TOrder',
            fields=[
                ('order_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('total_num', models.IntegerField(null=True)),
                ('total_price', models.FloatField(null=True)),
                ('create_time', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=40, null=True)),
                ('delivery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bookapp.TDelivery')),
            ],
            options={
                'db_table': 't_order',
            },
        ),
        migrations.CreateModel(
            name='TUser',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('nick_name', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=40, null=True)),
                ('password', models.CharField(max_length=40, null=True)),
                ('active_status', models.CharField(max_length=40, null=True)),
            ],
            options={
                'db_table': 't_user',
            },
        ),
        migrations.AddField(
            model_name='torder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bookapp.TUser'),
        ),
        migrations.AddField(
            model_name='tdelivery',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bookapp.TUser'),
        ),
        migrations.AddField(
            model_name='goodslist',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bookapp.TOrder'),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='catogray',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bookapp.TCatogray'),
        ),
    ]
