# Generated by Django 2.0.6 on 2019-05-23 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128, verbose_name='邮箱验证码')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 't_confirmcode',
            },
        ),
        migrations.RemoveField(
            model_name='tuser',
            name='active_status',
        ),
        migrations.AddField(
            model_name='tuser',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='tuser',
            name='salt',
            field=models.CharField(max_length=40, null=True, verbose_name='盐'),
        ),
        migrations.AddField(
            model_name='tuser',
            name='status',
            field=models.BooleanField(default=False, verbose_name='激活状态'),
        ),
        migrations.AddField(
            model_name='confirmcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapp.TUser', verbose_name='用户id'),
        ),
    ]
